name: experimentdataanalysis
channels:
  - conda-forge
dependencies:
  - python=3.5
  - jupyter=1.0.0
  - jupyter_contrib_nbextensions=0.2.6
  - matplotlib=2.0.0
  - numpy>=1.11.0
  - pyqt=4.11
  - scipy=0.19.0
  - spyder=3.1.3
  - sympy=1.0
#  - pip
#  - pip:

